### ISSUE TITLE
RD-MCL doesn't catch when Psi-BLAST finds no hits

### ISSUE THREAD

**Issue by KarlKeat** [biologyguy/RD-MCL#1]
When this happens, no checkpoint file is produced and things start breaking

**Comment by KarlKeat** [comment]
We probably need to break up all the commands in the Popen call into individual Popen calls and have error handling for if a certain file is not found.

**Comment by biologyguy** [comment]
Fixed by removing dependence on PSI-BLAST
commit 89747ec69b6def8bc8eaac93815da6e69c38428a
