### ISSUE TITLE
RD-MCL still crashes due to unnamed parent cluster

### ISSUE THREAD

**Issue by KarlKeat** [biologyguy/RD-MCL#2]
*\* Recursive MCL **
MCL runs processed: 9027. Sequences placed: 0/143. Run time: 2 days, 0 hrs, 29 min, 56 secTraceback (most recent call last):
  File "./rdmcl.py", line 1037, in <module>
    logging.warning("Total MCL runs: %s" % progress_dict["mcl_runs"])
  File "./rdmcl.py", line 547, in orthogroup_caller
    if master_cluster.name() != "group_0":
  File "./rdmcl.py", line 547, in orthogroup_caller
    if master_cluster.name() != "group_0":
  File "./rdmcl.py", line 528, in orthogroup_caller
    save_cluster()
  File "./rdmcl.py", line 164, in set_name
    raise ValueError("Parent of current cluster has not been named.\n%s" % self)
ValueError: Parent of current cluster has not been named.
['Nfl-Kkao', 'Nxa-Kkao', 'Nsq-Kkao', 'Xcg-Kkao', 'Gis-Kkao', 'Trf-Kkao']

**Comment by biologyguy** [comment]
I'm not sure exactly when this issue was resolved, but it's no longer a problem.
